const KEY="hallow.night.v2"; const D=window.HALLOW;
const NAV=[["cycle","CYCLE"],["ops","OPS"],["notes","NOTES"],["hold","HOLD"],["house","HOUSE"],["board","BOARD"],["wire","WIRE"],["codex","CODEX"],["log","LOG"]];
const MAPS=[
 {id:0,name:"PORCH",w:12,h:8,need:4,speed:560,walls:["3,3","4,3","5,3","6,3","7,3","8,3","5,1","5,2"],patrols:[{x:6,y:1,dx:1,dy:0},{x:10,y:4,dx:0,dy:1}]},
 {id:1,name:"HALL",w:12,h:8,need:5,speed:520,walls:["2,2","2,3","2,4","9,2","9,3","9,4","5,5","6,5","7,5"],patrols:[{x:4,y:1,dx:1,dy:0},{x:1,y:6,dx:1,dy:0},{x:10,y:2,dx:0,dy:1}]},
 {id:2,name:"KITCHEN",w:12,h:8,need:5,speed:500,walls:["1,3","2,3","3,3","3,4","8,1","8,2","8,3","4,6","5,6"],patrols:[{x:6,y:2,dx:1,dy:0},{x:2,y:5,dx:0,dy:1},{x:10,y:6,dx:-1,dy:0}]},
 {id:3,name:"STAIRS",w:12,h:8,need:5,speed:480,walls:["4,0","4,1","4,2","4,3","7,4","7,5","7,6","7,7","1,5","2,5"],patrols:[{x:2,y:1,dx:1,dy:0},{x:9,y:1,dx:0,dy:1},{x:5,y:6,dx:1,dy:0}]},
 {id:4,name:"LANDING",w:12,h:8,need:6,speed:460,walls:["0,3","1,3","2,3","9,3","10,3","11,3","5,1","6,1","5,6","6,6"],patrols:[{x:3,y:1,dx:0,dy:1},{x:8,y:1,dx:0,dy:1},{x:4,y:5,dx:1,dy:0},{x:1,y:7,dx:1,dy:0}]},
 {id:5,name:"BEDROOM",w:12,h:8,need:6,speed:440,walls:["2,1","2,2","3,2","8,1","8,2","7,2","4,4","5,4","6,4","5,5"],patrols:[{x:1,y:4,dx:0,dy:1},{x:10,y:3,dx:0,dy:1},{x:6,y:0,dx:1,dy:0}]},
 {id:6,name:"LOFT",w:12,h:8,need:6,speed:420,walls:["1,1","2,1","3,1","1,2","10,1","9,1","8,1","10,2","5,3","6,3","5,4"],patrols:[{x:4,y:2,dx:1,dy:0},{x:7,y:5,dx:-1,dy:0},{x:2,y:6,dx:1,dy:0},{x:11,y:4,dx:0,dy:1}]},
 {id:7,name:"ATTIC",w:12,h:8,need:7,speed:400,walls:["3,2","4,2","5,2","6,2","3,3","8,4","8,5","8,6","2,5","2,6","9,1"],patrols:[{x:1,y:1,dx:1,dy:0},{x:10,y:2,dx:0,dy:1},{x:4,y:6,dx:1,dy:0},{x:6,y:3,dx:1,dy:0}]}
];
function today(){const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");}
function seed(){return {streak:0,last:null,best:0,ops:[],notes:"",visits:0,houseBest:0,houseWins:0,winsBy:[],holds:0,sophie:false,wires:[],codex:[],log:[],map:0};}
function load(){try{return Object.assign(seed(),JSON.parse(localStorage.getItem(KEY)||"null")||{});}catch(e){return seed();}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
const state=load(); state.visits=(state.visits||0)+1; if(!Array.isArray(state.log)) state.log=[]; state.log.unshift({t:new Date().toISOString(),ev:"open",n:"desk opened"}); state.log=state.log.slice(0,80); save();
let view="cycle",dossier=null,hold={t:null,left:0,mode:"still"},game=null,openCodex=null,openWire=null;
const stage=document.getElementById("stage");
function toast(msg){const el=document.getElementById("toast"); el.hidden=false; el.textContent=msg; clearTimeout(toast._id); toast._id=setTimeout(()=>{el.hidden=true;},2800);}
function log(ev,n){state.log.unshift({t:new Date().toISOString(),ev,n}); state.log=state.log.slice(0,80); save();}
function unlockAll(){const ctx={streak:state.streak,wins:state.houseWins,holds:state.holds,visits:state.visits,codex:state.codex.length}; (D.wires||[]).forEach(w=>{if(state.wires.includes(w.id))return; if(Object.entries(w.need).every(([k,v])=>(ctx[k]||0)>=v)){state.wires.push(w.id); log("wire",w.title);}}); (D.codex||[]).forEach(c=>{if(state.codex.includes(c.id))return; if(Object.entries(c.need).every(([k,v])=>(ctx[k]||0)>=v)) state.codex.push(c.id);}); if(state.streak>=3||state.houseWins>=1) state.sophie=true; save();}
unlockAll();
function checkIn(){const t=today(); if(state.last===t){toast("already logged tonight."); return;} const y=new Date(); y.setDate(y.getDate()-1); const ymd=y.getFullYear()+"-"+String(y.getMonth()+1).padStart(2,"0")+"-"+String(y.getDate()).padStart(2,"0"); state.streak=state.last===ymd?state.streak+1:1; state.last=t; state.best=Math.max(state.best||0,state.streak); log("check","night "+state.streak); unlockAll(); toast("night cycle accepted · streak "+state.streak); render();}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&","<":"<",">":">","\"":""","'":"&#39;"}[c]));}
function brief(){const i=Math.abs(today().split("-").reduce((a,b)=>a+Number(b),0))%(D.briefs.length); return D.briefs[i];}
function renderNav(){document.getElementById("nav").innerHTML=NAV.map(([id,l])=>`<button data-view="${id}" class="${view===id?"on":""}">${l}</button>`).join("");}
function renderCycle(){const logged=state.last===today(); const open=state.ops.filter(o=>!o.done).length; stage.innerHTML=`<section class="hero"><p class="kicker">// night cycle · local · v2</p><h1>Come back<br><em>every night.</em></h1><p class="lede">${escapeHtml(brief())}</p></section><div class="grid three"><div class="panel"><div class="stat">${state.streak}<span>streak · best ${state.best||0}</span></div><div class="meta">last ${state.last||"never"}</div><button class="commit" id="checkBtn">${logged?"LOGGED":"CHECK IN"}</button></div><div class="panel"><div class="stat">${open}<span>open ops</span></div><div class="meta">holds ${state.holds} · visits ${state.visits}</div><button class="commit ghosty" data-go="ops">OPS</button></div><div class="panel"><div class="stat">${state.houseWins}<span>extracts</span></div><div class="meta">map ${state.map+1}/8 · ${MAPS[state.map].name}</div><button class="commit ghosty" data-go="house">HOUSE</button></div><div class="panel"><div class="stat">${state.wires.length}<span>wires / ${D.wires.length}</span></div><button class="commit ghosty" data-go="wire">WIRE</button></div><div class="panel"><div class="stat">${state.codex.length}<span>codex / ${D.codex.length}</span></div><button class="commit ghosty" data-go="codex">CODEX</button></div><div class="panel"><div class="stat">${state.sophie?"CRACKED":"SEALED"}<span>S-00</span></div><button class="commit ghosty" data-go="board">BOARD</button></div></div><div class="panel" style="margin-top:14px"><div class="meta">suggested ops</div><ul class="ops">${(D.opsSuggest||[]).map((s,i)=>`<li><button class="ghost" data-sug="${i}">+ ${escapeHtml(s)}</button></li>`).join("")}</ul></div>`; document.getElementById("checkBtn").onclick=checkIn;}
function renderOps(){stage.innerHTML=`<p class="kicker">// field list</p><h1 class="page">Ops</h1><div class="row" style="margin:18px 0"><input id="opIn" type="text" placeholder="one job." /><button class="commit" id="opAdd" style="margin:0">ADD</button></div><ul class="ops" id="ops"></ul>`; const ul=document.getElementById("ops"); ul.innerHTML=state.ops.map(o=>`<li class="${o.done?"done":""}"><input type="checkbox" ${o.done?"checked":""} data-tog="${o.id}"/><span>${escapeHtml(o.text)}</span><button class="x" data-kill="${o.id}">\u00d7</button></li>`).join("")||`<li class="meta">empty.</li>`; const add=()=>{const v=(document.getElementById("opIn").value||"").trim(); if(!v)return; state.ops.unshift({id:Date.now(),text:v,done:false}); document.getElementById("opIn").value=""; save(); render();}; document.getElementById("opAdd").onclick=add; document.getElementById("opIn").addEventListener("keydown",e=>{if(e.key==="Enter")add();}); ul.onclick=e=>{if(e.target.dataset.tog){const o=state.ops.find(x=>x.id==e.target.dataset.tog); if(o){o.done=!o.done; save(); render();}} if(e.target.dataset.kill){state.ops=state.ops.filter(x=>x.id!=e.target.dataset.kill); save(); render();}};}
function renderNotes(){stage.innerHTML=`<p class="kicker">// this machine only</p><h1 class="page">Notes</h1><p class="lede">No server.</p><textarea id="notes">${escapeHtml(state.notes)}</textarea>`; document.getElementById("notes").addEventListener("input",e=>{state.notes=e.target.value; save();});}
function paintHold(){const el=document.getElementById("holdFace"); if(!el)return; const m=Math.floor(hold.left/60),s=String(hold.left%60).padStart(2,"0"); el.textContent=hold.t?m+":"+s:"00:00"; document.getElementById("holdSub").textContent=hold.t?(hold.mode==="still"?"do not move.":"one job."):"armed";}
function startHold(secs,mode){clearInterval(hold.t); hold.mode=mode; hold.left=secs; hold.t=setInterval(()=>{hold.left--; if(hold.left<=0){clearInterval(hold.t); hold.t=null; hold.left=0; state.holds++; log("hold",mode); unlockAll(); toast(mode==="still"?"hold complete.":"focus clear."); save();} if(view==="hold") paintHold();},1000); paintHold();}
function renderHold(){stage.innerHTML=`<p class="kicker">// locke · ${state.holds} done</p><h1 class="page">Hold</h1><div class="panel" style="margin-top:24px;text-align:center"><div class="hold-face" id="holdFace">00:00</div><div class="meta" id="holdSub">armed</div><div class="row" style="justify-content:center;margin-top:18px"><button class="commit" data-h="60" data-m="still">STILL 1:00</button><button class="commit ghosty" data-h="300" data-m="still">STILL 5:00</button><button class="commit ghosty" data-h="1500" data-m="focus">FOCUS 25:00</button><button class="ghost" id="holdStop">ABORT</button></div></div>`; stage.querySelectorAll("[data-h]").forEach(b=>b.onclick=()=>startHold(+b.dataset.h,b.dataset.m)); document.getElementById("holdStop").onclick=()=>{clearInterval(hold.t); hold.t=null; hold.left=0; paintHold();}; paintHold();}
function renderWire(){if(openWire){const w=D.wires.find(x=>x.id===openWire); stage.innerHTML=`<button class="ghost" id="back">\u2190 wire list</button><p class="kicker">${w.from}</p><h1 class="page">${escapeHtml(w.title)}</h1><div class="panel wire"><p>${escapeHtml(w.body)}</p></div>`; document.getElementById("back").onclick=()=>{openWire=null; render();}; return;} stage.innerHTML=`<p class="kicker">// inbound ${state.wires.length}/${D.wires.length}</p><h1 class="page">Wire</h1><div class="list">${D.wires.map(w=>{const on=state.wires.includes(w.id); return `<button class="rowline ${on?"":"dim"}" data-w="${w.id}">${on?w.from+" · "+w.title:"LOCKED"}</button>`;}).join("")}</div>`;}
function renderCodex(){if(openCodex){const c=D.codex.find(x=>x.id===openCodex); stage.innerHTML=`<button class="ghost" id="back">\u2190 codex</button><h1 class="page">${escapeHtml(c.title)}</h1><div class="panel wire"><p>${escapeHtml(c.body)}</p></div>`; document.getElementById("back").onclick=()=>{openCodex=null; render();}; return;} stage.innerHTML=`<p class="kicker">// archive ${state.codex.length}/${D.codex.length}</p><h1 class="page">Codex</h1><div class="list">${D.codex.map(c=>{const on=state.codex.includes(c.id); return `<button class="rowline ${on?"":"dim"}" data-c="${c.id}">${on?c.title:"LOCKED"}</button>`;}).join("")}</div>`;}
function renderBoard(){if(dossier){const op=D.operatives.find(o=>o.id===dossier); stage.innerHTML=`<button class="ghost" id="back">\u2190 board</button><div class="dossier-grid"><div class="portrait ${op.locked?"sophie":""}"></div><div><p class="meta">${op.id} · ${op.callsign}</p><h2 class="page">${op.name}</h2><p class="meta">${op.role}</p><p class="lede">${escapeHtml(op.file)}</p><button class="commit ${op.locked?"pink":""}" id="deploy">${op.locked?(state.sophie?"SHE IS ALREADY LIVE":"FILE WILL NOT STAY LOCKED"):"DEPLOY"}</button></div></div>`; document.getElementById("back").onclick=()=>{dossier=null; render();}; document.getElementById("deploy").onclick=()=>toast(op.locked?"S-00 // the seal is cosmetic.":op.name+" on point."); return;} stage.innerHTML=`<p class="kicker">// eight names</p><h1 class="page">Choose your <em>operative</em>.</h1><section class="grid three" id="board"></section>`; document.getElementById("board").innerHTML=D.operatives.map(op=>{const lock=op.locked&&!state.sophie; return `<article class="card ${lock?"locked":""}" data-id="${op.id}">${lock?"<span class='seal'>LOCKED</span>":(op.locked?"<span class='seal'>CRACKED</span>":"")}<p class="id">${op.id}</p><h3>${op.name}</h3><p class="role">${op.role}</p><div class="bar"></div></article>`;}).join("");}
function renderLog(){stage.innerHTML=`<p class="kicker">// local history</p><h1 class="page">Log</h1><div class="list">${state.log.map(x=>`<div class="rowline dim">${escapeHtml((x.t||"").slice(0,16).replace("T"," "))} · ${escapeHtml(x.ev)} · ${escapeHtml(x.n||"")}</div>`).join("")}</div>`;}
function cellKey(x,y){return x+","+y;} function blocked(x,y){if(x<0||y<0||x>=game.W||y>=game.H)return true; return game.walls.has(cellKey(x,y));}
function newGame(id){const m=MAPS[id]; const walls=new Set(m.walls); const free=[]; for(let y=0;y<m.h;y++)for(let x=0;x<m.w;x++)if(!walls.has(cellKey(x,y))&&!(x===0&&y===0))free.push([x,y]); const pick=()=>free.splice(Math.floor(Math.random()*free.length),1)[0]; const intel=[]; for(let i=0;i<m.need;i++)if(free.length)intel.push(pick()); game={W:m.w,H:m.h,walls,you:[0,0],intel,patrols:m.patrols.map(p=>({...p})),got:0,alive:true,won:false,need:m.need,tick:null,speed:m.speed,name:m.name,id:m.id};}
function stepPatrols(){game.patrols.forEach(p=>{let nx=p.x+p.dx,ny=p.y+p.dy; if(blocked(nx,ny)){p.dx*=-1;p.dy*=-1;nx=p.x+p.dx;ny=p.y+p.dy;} if(!blocked(nx,ny)){p.x=nx;p.y=ny;}});}
function collide(){return game.patrols.some(p=>p.x===game.you[0]&&p.y===game.you[1]);}
function takeIntel(){const [x,y]=game.you; const i=game.intel.findIndex(p=>p[0]===x&&p[1]===y); if(i>=0){game.intel.splice(i,1); game.got++;} if(game.got>=game.need)game.won=true;}
function endHouse(win){clearInterval(game.tick); if(win){state.houseWins++; state.houseBest=Math.max(state.houseBest,game.got); if(!state.winsBy.includes(game.id))state.winsBy.push(game.id); if(state.map<MAPS.length-1&&game.id===state.map)state.map++; state.sophie=true; log("extract",game.name); unlockAll(); toast("EXTRACT · "+game.name);} else {log("burn",game.name); toast("seen. "+game.name+" keeps you.");} save(); paintHouse();}
function moveYou(dx,dy){if(!game||!game.alive||game.won)return; const nx=game.you[0]+dx,ny=game.you[1]+dy; if(blocked(nx,ny))return; game.you=[nx,ny]; if(collide()){game.alive=false; endHouse(false); return;} takeIntel(); if(game.won)endHouse(true); else paintHouse();}
function startLoop(){clearInterval(game&&game.tick); game.tick=setInterval(()=>{if(!game.alive||game.won)return; stepPatrols(); if(collide()){game.alive=false; endHouse(false);} else paintHouse();},game.speed);}
function paintHouse(){const grid=document.getElementById("hgrid"),info=document.getElementById("hinfo"); if(!grid||!game)return; let html=""; for(let y=0;y<game.H;y++)for(let x=0;x<game.W;x++){let cls="cell"; if(game.walls.has(cellKey(x,y)))cls+=" wall"; if(game.intel.some(p=>p[0]===x&&p[1]===y))cls+=" intel"; if(game.patrols.some(p=>p.x===x&&p.y===y))cls+=" patrol"; if(game.you[0]===x&&game.you[1]===y)cls+=" you"; html+=`<div class="${cls}"></div>`;} grid.innerHTML=html; info.innerHTML=game.won?`<p class="from">EXTRACT · ${game.name}</p><p>Last room was never empty.</p>`:!game.alive?`<p class="from">BURNED · ${game.name}</p><p>Restart.</p>`:`<p class="from">LIVE · ${game.name}</p><p>White you. Red patrol. Pink ${game.got}/${game.need}. WASD.</p>`;}
function renderHouse(){if(!game)newGame(state.map); stage.innerHTML=`<p class="kicker">// campaign ${state.winsBy.length}/8 · extracts ${state.houseWins}</p><h1 class="page">House</h1><div class="row" style="margin:12px 0">${MAPS.map((m,i)=>{const open=i<=state.map||state.winsBy.includes(i); return `<button class="ghost ${open?"":"dim"}" data-map="${i}">${i+1} ${m.name}${state.winsBy.includes(i)?" \u2713":""}</button>`;}).join("")}</div><div class="house-wrap"><div class="board-grid" id="hgrid"></div><div class="panel wire"><div id="hinfo"></div><button class="commit" id="hrestart">RESTART</button></div></div>`; document.getElementById("hrestart").onclick=()=>{newGame(game.id); startLoop(); paintHouse();}; startLoop(); paintHouse();}
const views={cycle:renderCycle,ops:renderOps,notes:renderNotes,hold:renderHold,house:renderHouse,board:renderBoard,wire:renderWire,codex:renderCodex,log:renderLog};
function render(){renderNav(); if(game&&view!=="house")clearInterval(game.tick); views[view](); document.getElementById("footLeft").textContent="HALLOW // "+view+" // "+state.visits+" visits";}
document.getElementById("nav").onclick=e=>{const b=e.target.closest("button[data-view]"); if(!b)return; view=b.dataset.view; dossier=openWire=openCodex=null; render();};
document.getElementById("stage").addEventListener("click",e=>{const go=e.target.closest("[data-go]"); if(go){view=go.dataset.go; render(); return;} const sug=e.target.closest("[data-sug]"); if(sug){state.ops.unshift({id:Date.now(),text:D.opsSuggest[+sug.dataset.sug],done:false}); save(); toast("op added"); return;} const card=e.target.closest(".card[data-id]"); if(card){dossier=card.dataset.id; render(); return;} const w=e.target.closest("[data-w]"); if(w&&state.wires.includes(w.dataset.w)){openWire=w.dataset.w; render(); return;} const c=e.target.closest("[data-c]"); if(c&&state.codex.includes(c.dataset.c)){openCodex=c.dataset.c; render(); return;} const mp=e.target.closest("[data-map]"); if(mp){const i=+mp.dataset.map; if(i<=state.map||state.winsBy.includes(i)){newGame(i); startLoop(); paintHouse();}}});
document.addEventListener("keydown",e=>{const map={1:"cycle",2:"ops",3:"notes",4:"hold",5:"house",6:"board",7:"wire",8:"codex",9:"log"}; if(map[e.key]){view=map[e.key]; dossier=openWire=openCodex=null; render(); return;} if(view==="house"&&game){if(e.key==="ArrowUp"||e.key==="w"){e.preventDefault(); moveYou(0,-1);} if(e.key==="ArrowDown"||e.key==="s"){e.preventDefault(); moveYou(0,1);} if(e.key==="ArrowLeft"||e.key==="a"){e.preventDefault(); moveYou(-1,0);} if(e.key==="ArrowRight"||e.key==="d"){e.preventDefault(); moveYou(1,0);}}});
function tickClock(){document.getElementById("clock").textContent=new Date().toLocaleTimeString("en-GB",{hour12:false});}
setInterval(tickClock,1000); tickClock(); render();
