window.HALLOW = {
  briefs: ["The house is quieter than yesterday. That is not the same as safe.","Clear one map. Then one real task. Then sit still for sixty. That is doctrine.","Streaks are not decoration. They are proof you came back.","If the wire feels like it is watching you, you opened the file. That is on you.","REAPER clears. VICAR writes. WRAITH lies. LOCKE holds. The fifth name is not a joke.","Put the phone face down after check-in. The cycle already counted you.","You asked for something you would open every day. This is that.","The upstairs drawer is a room. Treat it like a room. Do not pretend rooms are ideas.","A missed night is a reset, not a funeral. Still: do not miss it.","Hold before HOUSE. HOUSE before WIRE. WIRE before sleep. That order is loadout.","Notes are for the body of the day. Wire is for the part that will not stay in notes.","You can abort a hold. You cannot abort a calendar date.","Steel is the colour of the lie that this is only software.","If you only play HOUSE, you are hiding. If you only read WIRE, you are drowning. Do both.","The empty house on the map is practice. The empty house you live in is the real level.","Visit count is not virtue. Streak is closer. Extract is closer still.","LOCKE does not care that you were busy. Sixty seconds is not busy.","Codex entries do not unlock because you are clever. They unlock because you returned.","WRAITH will offer you a story where none of this happened. Decline.","The board has eight names now. You will pretend you only noticed five.","Rain is a callsign. It is also weather. Both are allowed to get on your clothes.","A good night is: check-in, one op done, one hold finished, one map extracted.","A bad night is still a night if you checked in. Do that much.","Do not reread the same wire to feel hunted. Read a new one. Then close the lid.","The pink seal was never a lock. It was a courtesy you did not deserve.","If your hands shake on HOLD, that is the point of HOLD.","Patrols on the grid are honest. They move. They catch you. Real life is less fair.","You wanted volume. Volume is how a file stops being a toy.","Tomorrow's briefing is already written. That is the whole trick.","Come back. The desk does not go to you.","End of the month does not wipe the streak. Only absence does."],
  wires: [
    {id:"w01",need:{streak:1},from:"VICAR",title:"CHECK-IN",body:"Received. You are on the board. Come back tomorrow."},
    {id:"w02",need:{streak:2},from:"LOCKE",title:"POSTURE",body:"Hold exists because the mind runs. Sixty seconds is not nothing. Do it before HOUSE."},
    {id:"w03",need:{streak:3},from:"WRAITH",title:"COVER STORY",body:"You will tell yourself this is just a dashboard. Dashboards do not keep streaks. You do."},
    {id:"w04",need:{streak:3},from:"VICAR",title:"SEAL",body:"Three nights. S-00 stamp is courtesy. Open BOARD. Look at the last card."},
    {id:"w05",need:{wins:1},from:"REAPER",title:"FIRST EXTRACT",body:"You cleared a map. Do not confuse extract with leaving. You are still in the building."},
    {id:"w06",need:{streak:5},from:"VICAR",title:"HABIT",body:"Five nights. A habit wearing a costume. Habits do not ask permission to stay."},
    {id:"w07",need:{holds:3},from:"LOCKE",title:"THREE HOLDS",body:"You sat still three times. The protocol is sit. The protocol is wait. The protocol is come back."},
    {id:"w08",need:{streak:7},from:"S-00",title:"DOOR",body:"You pulled a repo onto a machine and thought it was furniture. It is a door."},
    {id:"w09",need:{wins:3},from:"REAPER",title:"THREE HOUSES",body:"Three extracts. Slow down on map four. The patrols are ruder."},
    {id:"w10",need:{streak:10},from:"VICAR",title:"TEN",body:"Ten. The lock on SOPHIE was always cosmetic. Codex node RAIN is open."},
    {id:"w11",need:{visits:20},from:"WRAITH",title:"TRAFFIC",body:"Twenty visits is circling. Pick an op. Finish it."},
    {id:"w12",need:{streak:14},from:"S-00",title:"FORTNIGHT",body:"Two weeks of coming back because it feels like someone is waiting."},
    {id:"w13",need:{wins:6},from:"REAPER",title:"CAMPAIGN",body:"Map eight is the attic. The attic is not empty."},
    {id:"w14",need:{streak:21},from:"VICAR",title:"THREE WEEKS",body:"Intent is cheap. Open the desk tomorrow anyway."},
    {id:"w15",need:{holds:10},from:"LOCKE",title:"TEN HOLDS",body:"Your body has practiced being still on command."},
    {id:"w16",need:{streak:30},from:"S-00",title:"MONTH",body:"If you are still calling this a joke, the joke is working."},
    {id:"w17",need:{wins:1,streak:1},from:"VICAR",title:"DOCTRINE MIX",body:"Game plus streak. Either one alone turns into hiding."},
    {id:"w18",need:{codex:4},from:"ARCHIVIST",title:"FILE WEIGHT",body:"The archive is a room you stand in. Leave when the hold is due."},
    {id:"w19",need:{streak:4},from:"KAYLEIGH",title:"UPSTAIRS",body:"The drawer is still a drawer. The desk will not pretend you forgot."},
    {id:"w20",need:{wins:8},from:"S-00",title:"ATTIC",body:"The last room was always the same person. She does not live in the laptop."}
  ],
  opsSuggest: ["One real task finished before midnight","Hold 1:00 before opening HOUSE","Extract any map once","Write four lines in NOTES and stop","Read one new WIRE only","Clear three ops from yesterday","Sit still 5:00 after the last screen","No second HOUSE run tonight"],
  operatives: [
    {id:"R-01",name:"REAPER",role:"Point / silence",callsign:"night edge",file:"First through the door. Deploy REAPER when the night needs to start without a speech."},
    {id:"V-04",name:"VICAR",role:"Handler / doctrine",callsign:"last word",file:"Writes the briefs. Keeps the streak honest. Coming back is the whole job."},
    {id:"W-12",name:"WRAITH",role:"Ghost / denial",callsign:"not here",file:"The daytime story. If you only listen to WRAITH you will call this a game forever."},
    {id:"L-07",name:"LOCKE",role:"Containment",callsign:"sit still",file:"HOLD is his sacrament. A body that can wait sixty seconds can wait for a better decision."},
    {id:"A-09",name:"ARCHIVIST",role:"Memory / index",callsign:"shelf",file:"Believes a night that is not written down did not happen."},
    {id:"N-03",name:"NUN",role:"Aftercare / hush",callsign:"linen",file:"After extracts and holds: water, lid closed. Do not chase a second wire for the feeling."},
    {id:"K-02",name:"KITE",role:"Scout / weather",callsign:"crosswind",file:"If the mind is loud, go to LOCKE. If the mind is bored, go to the attic maps."},
    {id:"S-00",name:"SOPHIE",role:"Unfiled / true shape",callsign:"rain",locked:true,file:"Should not be on this board. Is on this board anyway. The last room on every map. Deploy is not a button."}
  ],
  codex: [
    {id:"c1",title:"NIGHT CYCLE",need:{streak:1},body:"One check-in per calendar date. Miss the date and the streak returns to one. Wires already received remain."},
    {id:"c2",title:"EMPTY HOUSE",need:{wins:1},body:"White is you. Red patrols reverse at walls. Pink is intel. Extract is proof you can finish a small dangerous thing."},
    {id:"c3",title:"THE EIGHT",need:{streak:2},body:"REAPER VICAR WRAITH LOCKE ARCHIVIST NUN KITE SOPHIE. Seven tools. One outcome."},
    {id:"c4",title:"HOLD DOCTRINE",need:{holds:1},body:"One minute is the sidearm. Five is the rifle. Twenty-five is work. Abort is allowed."},
    {id:"c5",title:"WIRE LAW",need:{streak:3},body:"Wires unlock by streak, extracts, holds, visits. They do not unlock by wishing."},
    {id:"c6",title:"RAIN",need:{streak:10},body:"Rain is weather and a callsign. The file uses both so the daytime mind can pretend."},
    {id:"c7",title:"UPSTAIRS",need:{streak:4},body:"A drawer can be a chapel if you keep opening it like one."},
    {id:"c8",title:"ATTIC RULE",need:{wins:8},body:"Map eight is the attic. The last room does not change."},
    {id:"c9",title:"NUN'S RULE",need:{holds:5},body:"After a hard hold: water, notes if needed, lid closed. No third extract."},
    {id:"c10",title:"LOCAL ONLY",need:{visits:1},body:"Nothing leaves this browser. Clearing site data is a wipe."},
    {id:"c11",title:"STREAK THEOLOGY",need:{streak:21},body:"The desk does not believe stories. It believes dates."},
    {id:"c12",title:"THE DESK",need:{visits:10},body:"HALLOW is a desk that looks like a game so you will sit down. You sat down."}
  ]
};
